### ISSUE TITLE
Issue with dis_recieve.py createPdu()

### ISSUE THREAD

**Issue by ajberlier** [open-dis/open-dis-python#19]
Created UDP socket 62040
Traceback (most recent call last):
  File ".\dis_receiver.py", line 41, in <module>
    recv()
  File ".\dis_receiver.py", line 30, in recv
    aPdu = createPdu(data)
  File "C:\Users\berliaj1\Anaconda3\lib\site-packages\opendis\PduFactory.py", line 92, in createPdu
    return getPdu(inputStream)
  File "C:\Users\berliaj1\Anaconda3\lib\site-packages\opendis\PduFactory.py", line 75, in getPdu
    pdu.parse(inputStream)
  File "C:\Users\berliaj1\Anaconda3\lib\site-packages\opendis\dis7.py", line 5128, in parse
    self.marking.parse(inputStream)
  File "C:\Users\berliaj1\Anaconda3\lib\site-packages\opendis\dis7.py", line 1356, in parse
    val = inputStream.read_byte()
  File "C:\Users\berliaj1\Anaconda3\lib\site-packages\opendis\DataInputStream.py", line 17, in read_byte
    return struct.unpack('b', self.stream.read(1))[0]
struct.error: unpack requires a buffer of 1 bytes

**Comment by leif81** [comment]
Line 1356 is in the Entity Marking parser of the Entity State PDU.

https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L1356

Could you share a Wireshark data capture of the PDU?

**Comment by leif81** [comment]
@ajberlierI started work on a unit test yestserday. So far I'm using just a sample ESPDU I have, but if I could get the sample ESPPDU from you that was causing the error that'd be better.

**Comment by leif81** [comment]
@ajberlier To be able to reproduce and fix this I'm going to need a sample ESPDU that causes the crash. Can you share that? I'm at a dead end until I get a sample from you. Thanks.

**Comment by leif81** [comment]
I can't reproduce the issue so I'm going to close. @ajberlier if this is still affecting you please reopen.
