### ISSUE TITLE
Divide by zero in RangeCoordinates.py

### ISSUE THREAD

**Issue by coderextreme** [open-dis/open-dis-python#24]
This change to open-dis-python will enable connectivity between open-dis-javascript (node-disnetworkclient) and  open-dis-python samples (previously, p was 0).

I have senders and receivers working in both languages, interoperable? Perhaps.

diff --git a/opendis/RangeCoordinates.py b/opendis/RangeCoordinates.py
index f28b4f2..5e24188 100644
--- a/opendis/RangeCoordinates.py
+++ b/opendis/RangeCoordinates.py
@@ -166,7 +166,7 @@ class GPS:
         #Initialize the variables to calculate lat and alt
         alt = 0
         N = self.wgs84.a
-        p = sqrt(x**2 + y**2)
+        p = sqrt(x**2 + y**2) + 0.001
         lat = 0
         previousLat = 90
         #Iterate until tolerance is reached

Fixes this error:

coderextreme@coderextreme-Kubuntu20:~/open-dis-python$ python3 examples/dis_receiver.py
Listening for DIS on UDP socket 1194
Traceback (most recent call last):
  File "examples/dis_receiver.py", line 39, in <module>
    recv()
  File "examples/dis_receiver.py", line 32, in recv
    lla = gps.ecef2lla(loc)
  File "/home/coderextreme/open-dis-python/opendis/RangeCoordinates.py", line 176, in ecef2lla
    lat = atan((z + self.wgs84.e**2 * N * sinLat) / p)
ZeroDivisionError: float division by zero

**Comment by leif81** [comment]
Thank-you for the report @coderextreme 

For `p = sqrt(x**2 + y**2)` to be 0, the x and y values must be 0 which sounds to me like bad data in the ESPDU packet. x and y should not be 0. I don't think the issue is with RangeCoordinates.py.

Can you check that x,y,z is being set to valid values in your ESPDU in open-dis-javascript? And if it is, then check that the data being received by open-dis-python matches.

**Comment by coderextreme** [comment]
One shouldn't crash if a client sends bad data. Isn't it obvious that x and y are both 0?

**Comment by leif81** [comment]
I expect there are many many ways to crash the code with bad data. The more interesting question is why are x and y zero. Were they just not set in the ESODU. Or is there an actual bug in the JavaScript marshalling and/or Python unmarshalling code when valid xy values are sent?
